services:
  eligibility-checker:
    build: .
    image: "docker.io/lucasmarctyd/eligibility-checker@sha256:2f788e80243032910ca8ebc9262ec3cb314c1d3fd89464560268b420a9453345" # Always provide FQDN image names!
    platform: linux/amd64
